# Generated by Django 4.1 on 2022-08-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Food', 'Food')], max_length=20, null=True),
        ),
    ]
